name: Check Helm Generation

on:
  push:
      branches:
        - 'main'
        - '[0-9]+.[1-9][0-9]*.x'
  pull_request:
    branches:
      - 'main'
      - '[0-9]+.[1-9][0-9]*.x'

jobs:
  helm-generation-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Helm
      uses: Azure/setup-helm@v3
      with:
        token: ${{ secrets.HELM_TOKEN }}

    - name: Generate current YAML
      run: |
        helm template helm/chart > current.yaml
    
    - name: Generate new Helm Chart
      run: make helm-package

    - name: Generate new YAML
      run: |
        helm template helm/chart > new.yaml
        
    - name: Compare YAML files
      run: |
        if ! diff -rq current.yaml new.yaml &>/dev/null; then 
          echo "Helm charts were not re-generated. Please regenerate them using make helm-template"
          exit 
        else
          echo ""
          echo "There are no changes in the manifests"
